### cloud-config-repo
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_demo
    username: demo_project
    password: Dp12345678
    driver-class-name: org.postgresql.Driver
  data:
    jdbc:
      repositories: true
  liquibase:
    enabled: true
    # default-schema: test_project

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE

### local
# spring:
#  application:
#    name: server
#  config:
#    import: optional:configserver:http://localhost:5000