version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_demo
      POSTGRES_USER: demo_project
      POSTGRES_PASSWORD: Dp12345678