geoeditor:
  well-service:
    name: server
    host: localhost:8081
    username: remote
    password: ENC(hh4P+7uz2giGnFPzBaq6iqRuSj7fBlSK99BOwf9oCP5/cdJum8R+PhU7lDN/PnKy)
spring:
  main:
    web-application-type: none

use:
  feign:
    client: true

jasypt:
  encryptor:
    password: sk091254